# Generated by Django 3.0.2 on 2021-06-25 03:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_Flag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='承認フラグID')),
                ('flag', models.CharField(max_length=5, verbose_name='承認フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='部署ID')),
                ('name', models.CharField(max_length=24, verbose_name='部署名')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='役職ID')),
                ('name', models.CharField(max_length=5, verbose_name='役職名')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Flag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='購入フラグID')),
                ('flag', models.CharField(max_length=5, verbose_name='購入フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='Ringisyo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='稟議書ID')),
                ('title', models.CharField(max_length=32, verbose_name='稟議書タイトル')),
                ('deadline', models.DateField(verbose_name='承認期限')),
                ('product_title', models.CharField(max_length=32, verbose_name='物品名')),
                ('trader_name', models.CharField(max_length=32, verbose_name='業者名')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.IntegerField(verbose_name='単価')),
                ('need_reason', models.CharField(max_length=512, verbose_name='必要理由')),
                ('trader_reason', models.CharField(max_length=512, verbose_name='業者選定理由')),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringisyo.Position')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='社員ID')),
                ('firstName', models.CharField(max_length=16, verbose_name='姓')),
                ('lastName', models.CharField(max_length=16, verbose_name='名')),
                ('birth', models.DateField(verbose_name='生年月日')),
                ('boss_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='上司ID')),
                ('mailAddress', models.CharField(max_length=64, verbose_name='メールアドレス')),
                ('salt', models.CharField(max_length=32, verbose_name='ソルト')),
                ('hashed_pw', models.CharField(max_length=64, verbose_name='パスワード')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringisyo.Department')),
                ('pos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringisyo.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Ringisyo_apv',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ringisyo.Ringisyo')),
                ('remarks', models.CharField(max_length=512, verbose_name='備考')),
                ('chief_apv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief', to='ringisyo.Approval_Flag', verbose_name='主任_承認')),
                ('director_apv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='ringisyo.Approval_Flag', verbose_name='部長_承認')),
                ('mDirector_apv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mDirector', to='ringisyo.Approval_Flag', verbose_name='常務_承認')),
                ('president_apv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='ringisyo.Approval_Flag', verbose_name='社長_承認')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringisyo.Purchase_Flag')),
            ],
        ),
    ]
